[registries.idle-app-core]
index = "sparse+https://raw.githubusercontent.com/idleai/app-core/cargo-index/"

[registries.idle-editchain]
index = "sparse+https://raw.githubusercontent.com/idleai/editchain/cargo-index/"

[registries.idle-host-tools]
index = "sparse+https://raw.githubusercontent.com/idleai/host-tools/cargo-index/"

[registries.idle-web-ui]
index = "sparse+https://raw.githubusercontent.com/idleai/web-ui/cargo-index/"
